### PR TITLE
New schema for generating IPA (International Phonetic Alphabet)

### PR DESCRIPTION
**Pull request by deepestblue**
New IPA script.
Renamed .ime file to NoInherentA.ime to better reflect its semantics.
Needed to add Dependent A to all schemes, so I could remove it from NoInherentA, and map it to a different output in IPA.map
Needed to add DIGITs to IPA.map, even though they make no sense here. I got an error otherwise; not sure how else to get around that. The error was "Fatal: Error parsing IME file for script: IPA, scheme: Ksharanam due to Invalid class name: DIGIT"

### CODE REVIEW

**Comment by ratreya** [comment]
Looks good. For the DIGIT problem, you can try removing the "{DIGIT} [DIGIT]" line from NoInherentA.ime which should allow you to drop all the DIGIT entries from the IPA and ISO map files.
Also can you edit [README.md](https://github.com/ratreya/Lipika_IME/blob/master/README.md) and add IPA to the list of supported scripts? Thanks!

**Comment by deepestblue** [comment]
I've edited the README. Regarding the DIGIT issue, the same way Devanagari, Bengali etc. include DIGITs, ISO-15919 also must include DIGITs, so that users can use numbers with letters. IPA, on the other hand ideally shouldn't include DIGITs. Ideas?

**Comment by ratreya** [comment]
LipikaIME engine will output the input as-is if it does not find a corresponding mapping for the input. Since DIGITS in IPA and ISO-15919 are the same for both input and output character, you can rely on the said functionality and drop the mapping for it. In fact, I pulled down your changes and tried it out and it works. This is not a big deal - if you are fine with it, I am good with merging as it is. Let me know.

**Comment by deepestblue** [comment]
> LipikaIME engine will output the input as-is if it does not find a corresponding mapping for the input. 

Doh, IIRC Google IME didn't work that way, so I never tested this with Lipika. Made the changes.

**Comment by ratreya** [comment]
Merged. Thank you!

**Pull request merged**
