### PR TITLE
Latin (ISO-15919) support

### PR DESCRIPTION
**Pull request by deepestblue**
I had to add all those 1-line .ime files; not sure if there's a better way.

Also, only the Ksharanam keymap is tested for this script.

### CODE REVIEW

**Comment by deepestblue** [comment]
I'll reopen this in a bit. I realised I omitted a bunch of characters in the map.

**Comment by ratreya** [comment]
I think you may be behind by three commits - can you merge tip of master from upstream?

**Comment by deepestblue** [comment]
Thanks; I think I've done that. Sorry, I'm a git n00b; if I've missed doing something let me know.

**Comment by ratreya** [comment]
Looks awesome! Thank you.

**Pull request merged**
